name: "Build"
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-latest
    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: "Setup CMake"
        uses: lukka/get-cmake@v3.26.4
      - name: "Setup vcpkg"
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: "**/vcpkg.json"
      - name: "Configure and build"
        uses: lukka/run-cmake@v10
        with:
          configurePreset: "ninja-x64-vcpkg-release"
          buildPreset: "x64-release"
